# Generated by Django 6.1 on 2026-08-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='available_copies_lte_total_copies')],
            },
        ),
    ]
